### ISSUE TITLE
FEATURE REQUEST: Add Bullshit image support.

### ISSUE THREAD

**Issue by k0mraid3** [mastercodeon314/NedrysBullshit#1]
Add initial support for bullshit images, starting with the bullshit white background Nedry-thing-ninja in form of a bullshit giff or other bullshit supported format. 

Bullshit=

https://github.com/mastercodeon314/NedrysBullshit/assets/62849592/3ea7008b-583b-43af-9b7e-a088062a6062

**Comment by mastercodeon314** [comment]
V2.0 now supports playing this clip that was posted. Both the audio clip and the video are played separately, and both are looped.
