### ISSUE TITLE
(BUG) Deadly Nedry

### ISSUE THREAD

**Issue by k0mraid3** [mastercodeon314/NedrysBullshit#2]
Nedry begins his nefarious auditory assault @ boot just after POST and will not **DIE. _EVER_**. 

Nedry also likes to **turn back on** the audio devices if you disable it via Device Manager. _Evil Bastard_. 

Nedry also seems **_impervious_** to a system restore. 

Purposed fix:
Burn C Drive, scrap project and lock this code on a USB drive, inside of a lead containment housing and sink it to the bottom of the Pacific ocean, to stay there. Forever.

**Comment by mastercodeon314** [comment]
Working as intended, no issue found
